apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-login
  namespace: rita-apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: ghcr-login
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{\"auths\":{\"ghcr.io\":{\"username\":\"SiderealMollusk\",\"password\":\"{{ .pat }}\",\"auth\":\"{{ printf \"%s:%s\" \"SiderealMollusk\" .pat | b64enc }}\"}}}"
  data:
  - secretKey: pat
    remoteRef:
      key: GH_PAT
      property: password
