---
- name: Install K3s agent
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['cp'][0]]['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars[groups['cp'][0]]['cluster_token'] }} sh -
  args:
    creates: /usr/local/bin/k3s
  when: hostvars[groups['cp'][0]]['cluster_token'] is defined
